// Sampled audio for the Wonder Workshop: short chiptune SFX plus an ambient
// music loop, generated by scripts/generate-workshop-audio.mjs into
// /audio/k5/workshop. Every call degrades gracefully — if a sample is
// missing (manifest empty, file 404s, or playback is blocked) the caller
// falls back to the WebAudio synth cues, so audio never hard-fails.
import manifest from "../data/workshopAudioManifest.json";

const hasAudio = () => typeof Audio !== "undefined";

const sfxCache = new Map();
let warmed = false;

function sampleUrl(id) {
  return manifest.items?.[id]?.file || null;
}

function getSample(id) {
  if (!hasAudio()) return null;
  const url = sampleUrl(id);
  if (!url) return null;
  if (!sfxCache.has(id)) {
    const element = new Audio(url);
    element.preload = "auto";
    sfxCache.set(id, element);
  }
  return sfxCache.get(id);
}

// Call on the first user gesture so short cues are decoded before they're
// needed. Safe to call repeatedly.
export function primeWonderAudio() {
  if (warmed || !hasAudio()) return;
  warmed = true;
  for (const id of Object.keys(manifest.items || {})) {
    if (manifest.items[id]?.kind === "music") continue;
    getSample(id);
  }
}

// Returns true if a sample actually started playing; false tells the caller
// to use its synth fallback instead.
export function playWonderSfx(id, { volume = 0.5 } = {}) {
  const sample = getSample(id);
  if (!sample) return false;
  try {
    const voice = sample.cloneNode();
    voice.volume = volume;
    const result = voice.play();
    if (result?.catch) result.catch(() => {});
    return true;
  } catch {
    return false;
  }
}

// Ambient loop for the workshop room. Owned separately from the narration
// audioBus so a story voice-over and the room music never fight.
let musicElement = null;

export const wonderMusic = {
  available() {
    return Boolean(sampleUrl("workshop-music")) && hasAudio();
  },
  start({ volume = 0.22 } = {}) {
    if (!this.available()) return false;
    if (!musicElement) {
      musicElement = new Audio(sampleUrl("workshop-music"));
      musicElement.loop = true;
      musicElement.preload = "auto";
    }
    musicElement.volume = volume;
    const result = musicElement.play();
    if (result?.catch) result.catch(() => {});
    return true;
  },
  stop() {
    if (!musicElement) return;
    musicElement.pause();
    try {
      musicElement.currentTime = 0;
    } catch {
      // Some browsers throw before metadata loads; stopping is enough.
    }
  },
  setVolume(volume) {
    if (musicElement) musicElement.volume = volume;
  },
};
